---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Сайт должен работать по протоколу https
  - Доступ к содержимому корзины доступен только в текущей сессии
  - При добавлении товара в корзину должен быть отправлен запрос на сервер
  - При переключении страниц должен быть запрос на сервер
  - При удалении товара из корзины должен быть запрос на сервер
  - В поле для ввода цены можно вводить только положительные целые числа
  - При пустом поле цены от, и заполненном, до, должны быть показаны товары от 0 до указанной цены
  - При пустом поле цены до, и заполненном, от, должны быть показаны товары от указанной цены
  - При пустых полях для ввода цены, должны показываться все товары
  - В фильтре при поиске с пустым полем должны выводиться все товары с учетом остальных фильтров
  - В фильтре при первой загрузке должны быть доступны все категории и бренды товаров
  - При количестве товаров меньше чем на 2 страницы, кнопки далее/предыдущая должны быть заблокированны
  - У фильтров должна быть кнопка очистить все фильтры
  - При выборе определенной категории товара, должны присутстовать только связанные с данной категорией бренды
  - При смене категории, все бренды должны очищаться
  - При вводе невалидных данных в поля, должны указываться соответствующие ошибки
  - В sessionStorage должен храниться id сессии пользователя
  - На странице не должно быть битых ссылок и картинок
  - На странице должен быть только один заголовок h1
  - На сайте должна быть реализована смена языка
  - Можно удалять товары из корзины по одному
  - В корзине должно быть указано количество и цена каждого добавленного товара
  - Все действия связанные с отправкой данных и переключения страниц, должны происходить без перезагрузки
  - При остутствии товара в корзине, на странцие корзины должно быть выведено сообшение "Ваша корзина пуста"
  - Должны отсутствовать ошибки и сообщения в консоли
  - В списке категории можно выбрать пустую опцию, для отображения всего товара
  - В корзине должна быть кнопка полной очистки
  - При удалении и добавлении товара должны всплывать модальные окна для подтверждения действия
  - При отправке данных на сервер должны отправлять только необходимые для данного запроса данные
  - Фильтры можно выбрать с помощью клавиатуры
  - На мобильной версии должен быть меню-бургер для фильтров
  - В корзине должна быть кнопка выхода из корзины
  - При обновлении страницы должны сохраняться добавленные товары и фильтры
  - Можно выбрать только один вариант цвета за раз
  - На странице товара должно указываться количество оставшегося товара
  - В фильтре есть возможность указать только товары с наличии или нет
  - У каждого товара должно быть описание и характеристики
